# Generated by Django 4.1.4 on 2022-12-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
